/**:
  ros__parameters:
    moveit_manage_controllers: False
    trajectory_execution:
      allowed_execution_duration_scaling: 1.2
      allowed_goal_duration_margin: 0.5
      allowed_start_tolerance: 0.01
    capabilities: move_group/MoveGroupExecuteTrajectoryAction
    publish_planning_scene: True
    publish_geometry_updates: True
    publish_state_updates: True
    publish_transforms_updates: True